[package]
name = "scry"
version = "0.17.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
shlex = "2"
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "sqlite",
    "chrono",
    "migrate",
] }
toml = "0.8"
tokio = { version = "1", features = ["full"] }
ratatui = "0.30"
ratatui-textarea = "0.9"
twox-hash = "2.1.4"
itertools = "0.15.0"
num_enum = "0.7.6"
strum = "0.28.0"
