-- Add migration script here
CREATE TABLE projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    entry_status_id   BIGINT,
    task_sorting_mode TEXT NOT NULL DEFAULT 'alphabetical',
    show_priority     BOOLEAN NOT NULL DEFAULT false,
    created_at        TIMESTAMPTZ NOT NULL
);
INSERT INTO projects (id, name, created_at) VALUES (1, 'default', now());
SELECT setval(pg_get_serial_sequence('projects', 'id'), (SELECT MAX(id) FROM projects));

CREATE TABLE statuses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    name       TEXT NOT NULL,
    position   INTEGER NOT NULL DEFAULT 0,
    color      TEXT,
    style      TEXT NOT NULL DEFAULT 'none',
    UNIQUE (project_id, name)
);
INSERT INTO statuses (id, project_id, name, position, style) VALUES (1, 1, 'todo', 0, 'unchecked');
INSERT INTO statuses (id, project_id, name, position, style) VALUES (2, 1, 'done', 1, 'checked');
SELECT setval(pg_get_serial_sequence('statuses', 'id'), (SELECT MAX(id) FROM statuses));

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL DEFAULT 1 REFERENCES projects(id),
    title       TEXT NOT NULL,
    description TEXT,
    priority    BIGINT NOT NULL DEFAULT 3,
    status_id   BIGINT NOT NULL DEFAULT 1 REFERENCES statuses(id),
    position    INTEGER NOT NULL DEFAULT 0,
    tags        TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    contents   TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE config (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
INSERT INTO config (key, value) VALUES ('active_project', '1');
